### PR TITLE
Set Formation as single CloudFormation Parameter

### LINKED ISSUE #816: Too many process types causes a CloudFormation Parameter Limit Error
If you have a docker-compose file with:

* More than 16 process types with no port mappings
* More than 5 process types with 1 port mapping

You can hit a CloudFormation error on deploy

```yaml
web: &web
  build: .
  command: bin/web
  ports:
    - 80:80
    - 443:80
worker: &worker
  <<: *web
  command: bundle exec rake jobs:work
  ports: []
w2:
  <<: *worker
  command: bundle exec rake jobs:w2
w3:
  <<: *worker
  command: bundle exec rake jobs:w3
w4:
  <<: *worker
  command: bundle exec rake jobs:w4
w5:
  <<: *worker
  command: bundle exec rake jobs:w5
w6:
  <<: *worker
  command: bundle exec rake jobs:w6
w7:
  <<: *worker
  command: bundle exec rake jobs:w7
w8:
  <<: *worker
  command: bundle exec rake jobs:w8
w9:
  <<: *worker
  command: bundle exec rake jobs:w9
w10:
  <<: *worker
  command: bundle exec rake jobs:w10
w11:
  <<: *worker
  command: bundle exec rake jobs:w11
```

```bash
$ convox deploy
...
Promoting RTMUEOBWWZA... ERROR: Template format error: Parameter count 61 is greater than max allowed 60`
```

### PR DESCRIPTION
**Pull request by nzoschke**
Fixes #816

## Release Playbook
- [x] Rebase against master
- [x] Release branch (20160628185122-formation-params)
- [x] Pass CI (https://circleci.com/gh/convox/rack/865)
- [x] Code review
- [x] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update staging rack
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

File: api/models/formation.go [hunk 1]
```diff
@@ -51,9 +52,19 @@ func ListFormation(app string) (Formation, error) {
 	formation := Formation{}
 
 	for _, me := range manifest {
-		count, _ := strconv.Atoi(a.Parameters[fmt.Sprintf("%sDesiredCount", UpperName(me.Name))])
-		memory, _ := strconv.Atoi(a.Parameters[fmt.Sprintf("%sMemory", UpperName(me.Name))])
-		cpu, _ := strconv.Atoi(a.Parameters[fmt.Sprintf("%sCpu", UpperName(me.Name))])
+		var count, memory, cpu int
+
+		if vals, ok := a.Parameters[fmt.Sprintf("%sFormation", UpperName(me.Name))]; ok {
+			parts := strings.SplitN(vals, ",", 3)
```
Comment (ddollar) [inline api/models/formation.go]: Check the length of parts here to avoid a panic

File: api/models/formation.go [hunk 2]
```diff
@@ -51,9 +52,19 @@ func ListFormation(app string) (Formation, error) {
...
+
+			count, _ = strconv.Atoi(parts[0])
```
Comment (ddollar) [inline api/models/formation.go]: Should check error results here since bad parsing could result in e.g. Scaling to 0

File: api/models/formation.go [hunk 3]
```diff
@@ -144,8 +151,36 @@ func SetFormation(app, process string, opts FormationOptions) error {
 		if int64(memory) > capacity.InstanceMemory {
 			return fmt.Errorf("requested memory %d greater than instance size %d", memory, capacity.InstanceMemory)
 		}
+	}
+
+	if vals, ok := a.Parameters[fmt.Sprintf("%sFormation", UpperName(process))]; ok {
+		parts := strings.SplitN(vals, ",", 3)
```
Comment (ddollar) [inline api/models/formation.go]: Check length of parts here

File: api/models/formation.go (hunk 1 above)
Comment (nzoschke) [inline api/models/formation.go]: Good call. One more pass to review validation and to add some tests certainly wouldn't hurt.

File: api/models/release.go [hunk 4]
```diff
@@ -174,12 +169,37 @@ func (r *Release) Promote() error {
...
-
 	if err != nil {
 		return err
 	}
 
 	for _, entry := range manifest {
+		// set all of WebCount=1, WebCpu=0, WebMemory=256 and WebFormation=1,0,256 style parameters
+		// so new deploys and rollbacks have the expected parameters
+		if vals, ok := app.Parameters[fmt.Sprintf("%sFormation", UpperName(entry.Name))]; ok {
+			parts := strings.SplitN(vals, ",", 3)
```
Comment (ddollar) [inline api/models/release.go]: Check length of parts
