### PR TITLE
Use .netrc for build credentials

### LINKED ISSUE #771: Clone additional GitHub private repos during build
As requested from frank in Slack:

>  if a repo has a dependency from another private repo. then `git clone` during build would fail.

### LINKED ISSUE #833: Dont log GitHub, etc. secrets in build output
Build output logs and saves the API key from GitHub. This should be masked.

```
$ convox builds info BKIYPLJNHZH --app myapp
RUNNING: git clone --progress https://API_KEY@github.com/my/repo.git src
RUNNING: git submodule update --init --recursive
RUNNING: git checkout f552b6afc02c9fbc372769f78138f87bda08685d
RUNNING: git submodule update --recursive
RUNNING: /usr/local/bin/git-restore-mtime .
...
```

### PR DESCRIPTION
**Pull request by MiguelMoll**
The `.netrc` file lives inside a container to help authorize private git repos.

Also made switch to logging a warning if `git submodule` fails instead of bailing on a build.

Fixes #771
Fixes #833 

## Release Playbook
- [x] Rebase against master
- [x] Release branch ()
- [x] Pass CI ()
- [x] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update staging rack
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ci8VNEBH&#x2F;281-github-private-build-token"> GitHub private build token</a>

File: api/cmd/build/main.go [hunk 1]
```diff
@@ -123,22 +123,43 @@ func cloneGit(s string) {
...
 	}
 
+	err = ioutil.WriteFile("/root/.netrc", []byte(fmt.Sprintf("machine %s login %s", u.Host, u.User.Username())), 0700)
+	if err != nil {
+		fmt.Println("WARNING: Failed to write to .netrc; git might fail: ", err)
+	}
+
 	writeAsset("/usr/local/bin/git-restore-mtime", "git-restore-mtime", 0755, nil)
 
 	run(".", "git", "clone", "--progress", repo, "src")
```
Comment (nzoschke) [inline api/cmd/build/main.go]: If the .netrc strategy works, you should be able to remove u.User from the repo argument, which would fix https://github.com/convox/rack/issues/833

Comment (nzoschke) [inline api/cmd/build/main.go]: SSH mode does this on line 112

Comment (MiguelMoll) [inline api/cmd/build/main.go]: I like it. Done!

**Comment by nzoschke** [comment]
this looks great.

**Comment by MiguelMoll** [comment]
Example output:
```
convox builds info BRCOWEZXEMP
RUNNING: git clone --progress https://github.com/convox/fake-publi-repo.git src
RUNNING: git submodule update --init --recursive
Submodule 'fake-private-repo' (https://github.com/convox/fake-private-repo.git) registered for path 'fake-private-repo'
Submodule path 'fake-private-repo': checked out 'dd41c4403cddb598490cbabc31ddd512556ba1ff'
RUNNING: git checkout b9d76b1ced8f7fa80db19ed3840c33448891cda1
RUNNING: git submodule update --recursive
RUNNING: /usr/local/bin/git-restore-mtime .
RUNNING: docker pull httpd
Using default tag: latest
```

No tokens logged. :+1:

File: api/cmd/build/main.go (hunk 1 above)
Comment (awsmsrc) [inline api/cmd/build/main.go]: @MiguelMoll @nzoschke I think this has broken gitlab deployments
